# Generated by Django 5.2.1 on 2025-05-29 04:34

import Apps.Cuna.models.Inscription
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('credits', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('bimester', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
                ('year', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150)),
                ('father_surname', models.CharField(max_length=100)),
                ('mother_surname', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['names', 'father_surname', 'mother_surname'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=155)),
                ('father_surname', models.CharField(max_length=155)),
                ('mother_surname', models.CharField(max_length=155)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('show_phone', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['names', 'father_surname', 'mother_surname'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cui', models.IntegerField(blank=True, null=True, unique=True)),
                ('names', models.CharField(max_length=155)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('proxy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='Cuna.proxy')),
            ],
            options={
                'ordering': ['cui', 'names'],
            },
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('U', 'Único')], default='U', max_length=1)),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuna.teacher')),
            ],
            options={
                'ordering': ['year_course', 'group'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='Cuna.workload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YearCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('curriculum', models.IntegerField(choices=[(2017, 'Plan 2017'), (2023, 'Plan 2023')], default=2023)),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(related_name='year_courses', to='Cuna.course')),
            ],
            options={
                'ordering': ['curriculum', 'year'],
                'unique_together': {('curriculum', 'year')},
            },
        ),
        migrations.AddField(
            model_name='workload',
            name='year_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cuna.yearcourse'),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuna.student', validators=[Apps.Cuna.models.Inscription.validate_even])),
                ('workload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuna.workload')),
            ],
            options={
                'ordering': ['workload', 'student', 'created'],
                'constraints': [models.UniqueConstraint(fields=('workload', 'student'), name='unique_inscription')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='workload',
            unique_together={('year_course', 'group')},
        ),
    ]
