# Generated by Django 5.2.1 on 2025-06-06 06:01

import Apps.Cuna.models.Inscription
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='workload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='Cuna.workload'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuna.student', validators=[Apps.Cuna.models.Inscription.validate_even]),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='workload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuna.workload'),
        ),
        migrations.AlterField(
            model_name='student',
            name='proxy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='Cuna.proxy'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuna.teacher'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='year_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cuna.yearcourse'),
        ),
        migrations.AlterField(
            model_name='yearcourse',
            name='courses',
            field=models.ManyToManyField(related_name='year_courses', to='Cuna.course'),
        ),
    ]
