# Generated by Django 5.2.1 on 2025-06-16 02:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuna', '0002_alter_announcement_workload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('EXAM', 'Examen'), ('PRACTICE', 'Práctica'), ('HOMEWORK', 'Tarea'), ('PROJECT', 'Proyecto'), ('PARTICIPATION', 'Participación'), ('FINAL', 'Nota Final')], default='EXAM', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)])),
                ('max_score', models.DecimalField(decimal_places=2, default=20.0, max_digits=4)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('evaluation_date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Peso de la evaluación para el promedio', max_digits=3)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='Cuna.inscription')),
            ],
            options={
                'ordering': ['inscription', 'evaluation_date', 'evaluation_type'],
                'unique_together': {('inscription', 'evaluation_type', 'description')},
            },
        ),
    ]
